export const employees = [
  {
    id: 1,
    name: "Ravi Saini",
    email: "ravi@saini.com",
    password: "123",
    taskCounts: { active: 8, newTask: 6, completed: 3, failed: 1 },
    nextId: 19 ,
    tasks: [
      { id: 1 ,status: "active", taskTitle: "Create Dashboard UI", taskDescription: "Design the main dashboard interfaceDesign the main dashboard interfaceDesign the main dashboard interfaceDesign the main dashboard interfaceDesign the main dashboard interfaceDesign the main dashboard interfaceDesign the main dashboard interface", taskDate: "2025-07-15", category: "Frontend" },
      { id: 2 ,status: "active", taskTitle: "Fix CSS Grid Bug", taskDescription: "Resolve layout issues in admin panel", taskDate: "2025-07-16", category: "Frontend" },
      { id: 3 ,status: "active", taskTitle: "Fix CSS Grid Bug", taskDescription: "Resolve layout issues in admin panel", taskDate: "2025-07-16", category: "Frontend" },
      { id: 4 ,status: "active", taskTitle: "Fix CSS Grid Bug", taskDescription: "Resolve layout issues in admin panel", taskDate: "2025-07-16", category: "Frontend" },
      { id: 5 ,status: "active", taskTitle: "Fix CSS Grid Bug", taskDescription: "Resolve layout issues in admin panel", taskDate: "2025-07-16", category: "Frontend" },
      { id: 6 ,status: "active", taskTitle: "Fix CSS Grid Bug", taskDescription: "Resolve layout issues in admin panel", taskDate: "2025-07-16", category: "Frontend" },
      { id: 7 ,status: "active", taskTitle: "Fix CSS Grid Bug", taskDescription: "Resolve layout issues in admin panel", taskDate: "2025-07-16", category: "Frontend" },
      { id: 8 ,status: "active", taskTitle: "Fix CSS Grid Bug", taskDescription: "Resolve layout issues in admin panel", taskDate: "2025-07-16", category: "Frontend" },
      { id: 9 ,status: "newTask", taskTitle: "Add Route Guards", taskDescription: "Secure private routes using auth state", taskDate: "2025-07-17", category: "Security" },
      { id: 10 ,status: "newTask", taskTitle: "Add Route Guards", taskDescription: "Secure private routes using auth state", taskDate: "2025-07-17", category: "Security" },
      { id: 11 ,status: "newTask", taskTitle: "Add Route Guards", taskDescription: "Secure private routes using auth state", taskDate: "2025-07-17", category: "Security" },
      { id: 12 ,status: "newTask", taskTitle: "Add Route Guards", taskDescription: "Secure private routes using auth state", taskDate: "2025-07-17", category: "Security" },
      { id: 13 ,status: "newTask", taskTitle: "Add Route Guards", taskDescription: "Secure private routes using auth state", taskDate: "2025-07-17", category: "Security" },
      { id: 14 ,status: "newTask", taskTitle: "Add Route Guards", taskDescription: "Secure private routes using auth state", taskDate: "2025-07-17", category: "Security" },
      { id: 15 ,status: "completed", taskTitle: "Firebase Auth Integration", taskDescription: "Set up email/password login", taskDate: "2025-07-10", category: "Backend" },
      { id: 16 ,status: "completed", taskTitle: "Tailwind Setup", taskDescription: "Install and configure Tailwind", taskDate: "2025-07-08", category: "Frontend" },
      { id: 17 ,status: "completed", taskTitle: "Figma Design Export", taskDescription: "Export and slice UI elements", taskDate: "2025-07-05", category: "Design" },
      { id: 18 ,status: "failed", taskTitle: "Stripe Setup", taskDescription: "Could not integrate payment gateway", taskDate: "2025-07-12", category: "Payments" },
    ],
  },
  {
    id: 2,
    name: "Simran Saini",
    email: "simran@saini.com",
    password: "123",
    taskCounts: { active: 1, newTask: 2, completed: 2, failed: 0 },
    nextId:  6,
    tasks: [
      { id: 1, status: "active", taskTitle: "Create Contact Form", taskDescription: "With validation and error handling", taskDate: "2025-07-17", category: "Frontend" },
      { id: 2, status: "newTask", taskTitle: "SEO Optimization", taskDescription: "Improve meta tags, sitemap, robots.txt", taskDate: "2025-07-18", category: "Marketing" },
      { id: 3, status: "newTask", taskTitle: "Add Prettier Config", taskDescription: "Standardize code formatting", taskDate: "2025-07-18", category: "DevOps" },
      { id: 4, status: "completed", taskTitle: "Dark Mode Toggle", taskDescription: "Switch themes via context", taskDate: "2025-07-12", category: "UI/UX" },
      { id: 5, status: "completed", taskTitle: "Vercel Deployment", taskDescription: "Push to GitHub & deploy", taskDate: "2025-07-14", category: "Deployment" },
    ],
  },
  {
    id: 3,
    name: "Arjun Saini",
    email: "arjun@saini.com",
    password: "123",
    taskCounts: { active: 0, newTask: 1, completed: 1, failed: 2 },
    nextId:  5,
    tasks: [
      {id : 1, status: "newTask", taskTitle: "Skeleton Project", taskDescription: "Initialize boilerplate", taskDate: "2025-07-18", category: "Setup" },
      {id : 2, status: "completed", taskTitle: "GitHub Setup", taskDescription: "Create repo and README", taskDate: "2025-07-08", category: "DevOps" },
      {id : 3, status: "failed", taskTitle: "Live Chat Module", taskDescription: "Integration failed with sockets", taskDate: "2025-07-11", category: "Backend" },
      {id : 4, status: "failed", taskTitle: "Redux Toolkit Setup", taskDescription: "Conflicts with React Query", taskDate: "2025-07-10", category: "State Management" },
    ],
  },
  {
    id: 4,
    name: "Meena Saini",
    email: "meena@saini.com",
    password: "123",
    taskCounts: { active: 1, newTask: 2, completed: 1, failed: 1 },
    nextId: 6 ,
    tasks: [
      {id: 1, status: "active", taskTitle: "Google Fonts Integration", taskDescription: "Use modern web typography", taskDate: "2025-07-14", category: "Frontend" },
      {id: 2, status: "newTask", taskTitle: "Set Up React Helmet", taskDescription: "Manage document head", taskDate: "2025-07-18", category: "SEO" },
      {id: 3, status: "newTask", taskTitle: "API Mocking with MSW", taskDescription: "Use Mock Service Worker for local dev", taskDate: "2025-07-18", category: "Testing" },
      {id: 4, status: "completed", taskTitle: "Responsive Sidebar", taskDescription: "CSS + Flexbox version of sidebar", taskDate: "2025-07-10", category: "UI/UX" },
      {id: 5, status: "failed", taskTitle: "EmailJS Integration", taskDescription: "Mail service timed out", taskDate: "2025-07-11", category: "Third Party" },
    ],
  },
  {
    id: 5,
    name: "Aman Saini",
    email: "aman@saini.com",
    password: "123",
    taskCounts: { active: 2, newTask: 0, completed: 1, failed: 0 },
    nextId: 4 ,
    tasks: [
      {id:1, status: "active", taskTitle: "Refactor Navbar", taskDescription: "Convert class to functional component", taskDate: "2025-07-16", category: "Frontend" },
      {id:2, status: "active", taskTitle: "Setup React Router", taskDescription: "Add page routing", taskDate: "2025-07-17", category: "Routing" },
      {id:3, status: "completed", taskTitle: "Setup Git Workflow", taskDescription: "Add dev and feature branches", taskDate: "2025-07-10", category: "DevOps" },
    ],
  },
  {
    id: 6,
    name: "Tanya Saini",
    email: "tanya@saini.com",
    password: "123",
    taskCounts: { active: 0, newTask: 1, completed: 2, failed: 1 },
    nextId: 5  ,
    tasks: [
      { id:1,status: "newTask", taskTitle: "React Context for Theme", taskDescription: "Global state for dark/light", taskDate: "2025-07-18", category: "State Management" },
      { id:2,status: "completed", taskTitle: "Landing Page", taskDescription: "Design and code hero section", taskDate: "2025-07-09", category: "Frontend" },
      { id:3,status: "completed", taskTitle: "Add favicon & meta", taskDescription: "For branding and SEO", taskDate: "2025-07-08", category: "Branding" },
      { id:4,status: "failed", taskTitle: "Netlify Forms", taskDescription: "Not submitting properly", taskDate: "2025-07-11", category: "DevOps" },
    ],
  },
  {
    id: 7,
    name: "Karan Saini",
    email: "karan@saini.com",
    password: "123",
    taskCounts: { active: 1, newTask: 1, completed: 2, failed: 0 },
    nextId: 5 ,
    tasks: [
      { id:1,status: "active", taskTitle: "Navbar Accessibility", taskDescription: "Ensure keyboard nav and ARIA roles", taskDate: "2025-07-16", category: "Accessibility" },
      { id:2,status: "newTask", taskTitle: "Implement Lazy Loading", taskDescription: "Code-splitting with React.lazy", taskDate: "2025-07-18", category: "Performance" },
      { id:3,status: "completed", taskTitle: "404 Page", taskDescription: "Custom route fallback page", taskDate: "2025-07-08", category: "Routing" },
      { id:4,status: "completed", taskTitle: "Custom Button Component", taskDescription: "Reusable styled button", taskDate: "2025-07-06", category: "UI/UX" },
    ],
  },
  {
    id: 8,
    name: "Pooja Saini",
    email: "pooja@saini.com",
    password: "123",
    taskCounts: { active: 1, newTask: 1, completed: 1, failed: 1 },
    nextId: 5,
    tasks: [
      {id:1, status: "active", taskTitle: "Form Validation with Yup", taskDescription: "Handle nested forms", taskDate: "2025-07-17", category: "Forms" },
      {id:2, status: "newTask", taskTitle: "Write Custom Hook", taskDescription: "useWindowWidth for responsive design", taskDate: "2025-07-18", category: "Hooks" },
      {id:3, status: "completed", taskTitle: "Blog Layout", taskDescription: "Use grid for posts and sidebar", taskDate: "2025-07-07", category: "Frontend" },
      {id:4, status: "failed", taskTitle: "React i18n", taskDescription: "Failed to configure translation files", taskDate: "2025-07-12", category: "Localization" },
    ],
  },
  {
    id: 9,
    name: "Nikhil Saini",
    email: "nikhil@saini.com",
    password: "123",
    taskCounts: { active: 0, newTask: 2, completed: 2, failed: 0 },
    nextId: 5 ,
    tasks: [
      {id:1, status: "newTask", taskTitle: "Search Functionality", taskDescription: "Debounced input with results", taskDate: "2025-07-18", category: "Frontend" },
      {id:2, status: "newTask", taskTitle: "UseMemo for Performance", taskDescription: "Avoid re-computations", taskDate: "2025-07-18", category: "Performance" },
      {id:3, status: "completed", taskTitle: "React Router v6 Setup", taskDescription: "Nested and dynamic routing", taskDate: "2025-07-11", category: "Routing" },
      {id:4, status: "completed", taskTitle: "Install Axios", taskDescription: "Setup instance and interceptors", taskDate: "2025-07-08", category: "API" },
    ],
  },
  {
    id: 10,
    name: "Divya Saini",
    email: "divya@saini.com",
    password: "123",
    taskCounts: { active: 1, newTask: 0, completed: 2, failed: 1 },
    nextId: 5 ,
    tasks: [
      {id:1, status: "active", taskTitle: "Carousel Component", taskDescription: "Auto slide + manual control", taskDate: "2025-07-16", category: "Frontend" },
      {id:2, status: "completed", taskTitle: "Install FontAwesome", taskDescription: "Add icons across UI", taskDate: "2025-07-10", category: "Frontend" },
      {id:3, status: "completed", taskTitle: "Responsive Cards", taskDescription: "Grid layout with media queries", taskDate: "2025-07-09", category: "UI/UX" },
      {id:4, status: "failed", taskTitle: "Fetch from Unsplash", taskDescription: "API rate limit error", taskDate: "2025-07-12", category: "API" },
    ],
  },
  {
    id: 11,
    name: "Ritika Saini",
    email: "ritika@saini.com",
    password: "123",
    taskCounts: { active: 1, newTask: 1, completed: 1, failed: 1 },
    nextId: 5 ,
    tasks: [
      {id:1, status: "active", taskTitle: "File Upload to Cloudinary", taskDescription: "Drag & drop image upload", taskDate: "2025-07-17", category: "Media" },
      {id:2, status: "newTask", taskTitle: "React Table Setup", taskDescription: "Paginated and sortable table", taskDate: "2025-07-18", category: "Data Display" },
      {id:3, status: "completed", taskTitle: "Integrate Chart.js", taskDescription: "Bar chart for stats dashboard", taskDate: "2025-07-07", category: "Visualization" },
      {id:4, status: "failed", taskTitle: "CSS Animation", taskDescription: "Bounce not working on hover", taskDate: "2025-07-12", category: "UI/UX" },
    ],
  },
  {
    id: 12,
    name: "Yash Saini",
    email: "yash@saini.com",
    password: "123",
    taskCounts: { active: 0, newTask: 1, completed: 2, failed: 1 },
    nextId: 5 ,
    tasks: [
      {id:1, status: "newTask", taskTitle: "Install React Query", taskDescription: "For data caching and fetch control", taskDate: "2025-07-18", category: "State Management" },
      {id:2, status: "completed", taskTitle: "Setup Husky Hooks", taskDescription: "Run lint & format before commit", taskDate: "2025-07-08", category: "DevOps" },
      {id:3, status: "completed", taskTitle: "Footer Component", taskDescription: "Sticky and responsive footer", taskDate: "2025-07-06", category: "Frontend" },
      {id:4, status: "failed", taskTitle: "Google Maps Embed", taskDescription: "API not rendering on prod", taskDate: "2025-07-11", category: "Third Party" },
    ],
  },
];